version: '3'

services:
  findAFriend-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker1234
      - POSTGRESQL_DATABASE=findafriend